name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  jest:

    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x, 16.x]
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run test:all:cov
    - run: npm i make-coverage-badge -g
    - run: make-coverage-badge --report-path ./coverage/packages/core/coverage-summary.json --output-path ./coverage/packages/core/coverage.svg
    - run: make-coverage-badge --report-path ./coverage/packages/common/coverage-summary.json --output-path ./coverage/packages/common/coverage.svg

    - name: Upload core coverage
      uses: actions/upload-artifact@v2
      with:
        name: core.coverage.svg
        path: ./coverage/packages/core/coverage.svg

    - name: Upload common coverage
      uses: actions/upload-artifact@v2
      with:
        name: common.coverage.svg
        path: ./coverage/packages/common/coverage.svg
